version: "3.8"
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fase4
    ports:
      - "3306:3306"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - tech-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  ms-customer:
    build: ./ms-customer
    container_name: ms-customer
    ports:
      - "8081:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - tech-network

  ms-product:
    build: ./ms-product
    container_name: ms-product
    ports:
      - "8082:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - tech-network

  ms-order:
    build: ./ms-order
    container_name: ms-order
    ports:
      - "8083:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - tech-network

  ms-logistic:
    build: ./ms-logistic
    container_name: ms-logistic
    ports:
      - "8084:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - tech-network

  ms-gateway:
    build: ./ms-gateway
    container_name: ms-gateway
    ports:
      - "8080:8080"
    depends_on:
      ms-customer:
        condition: service_started
      ms-product:
        condition: service_started
      ms-order:
        condition: service_started
      ms-logistic:
        condition: service_started
    networks:
      - tech-network

networks:
  tech-network:
    driver: bridge
