CREATE DATABASE IF NOT EXISTS ms_product;
CREATE DATABASE IF NOT EXISTS ms_customer;
CREATE DATABASE IF NOT EXISTS ms_order;
CREATE DATABASE IF NOT EXISTS ms_logistic;
CREATE DATABASE IF NOT EXISTS ms_gateway;
